package com.central.notification_service.model;

import jakarta.persistence.*;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.AllArgsConstructor;
import java.time.LocalDateTime;

@Entity
@Table(name = "central_notifications")
@Data // Generates getters, setters, toString, equals, and hashCode
@NoArgsConstructor // Generates a no-args constructor
@AllArgsConstructor // Generates an all-args constructor
@Builder
public class Notification {

    /**
     * Corresponds to OpenAPI field 'notificationId' (type: integer).
     * Used as the Primary Key and is auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long notificationId;

    /**
     * Corresponds to OpenAPI field 'transactionId' (type: string).
     * Typically stored as a UUID, but using String (VARCHAR) here as per your spec.
     */
    @Column(name = "transaction_id", nullable = false)
    private String transactionId;

    /**
     * Corresponds to OpenAPI field 'userId' (type: string).
     * The ID of the recipient user.
     */
    @Column(name = "user_id", nullable = false)
    private String userId;

    /**
     * Corresponds to OpenAPI field 'type' (type: string, enum: TRANSACTION_SUCCESS, REWARD_GRANTED, TRANSACTION_FAILED).
     * Stored as a String in the database.
     */
    @Column(name = "type", nullable = false)
    @Enumerated(EnumType.STRING) // Maps Java Enum to String in the DB
    private NotificationType type;

    /**
     * Corresponds to OpenAPI field 'subject' (type: string).
     */
    @Column(name = "subject")
    private String subject;

    /**
     * Corresponds to OpenAPI field 'content' (type: string).
     * Using 'TEXT' for potentially long content.
     */
    @Column(name = "content", columnDefinition = "TEXT")
    private String content;

    /**
     * Corresponds to OpenAPI field 'channel' (type: string, enum: EMAIL, SMS, PUSH).
     * Stored as a String in the database.
     */
    @Column(name = "channel")
    @Enumerated(EnumType.STRING)
    private NotificationChannel channel;

    /**
     * Corresponds to OpenAPI field 'sentAt' (type: string, format: date-time).
     * Mapped to Java's LocalDateTime, storing the exact time the notification was sent.
     */
    @Column(name = "sent_at", nullable = false)
    private LocalDateTime sentAt;
}